apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: ArgoCD
  labels:
    move2kube.konveyor.io/built-in: true
spec:
  class: "ArgoCD"
  directoryDetect:
    levels: 0
  consumes:
    IR:
      merge: true
  dependency:
    matchLabels:
      move2kube.konveyor.io/kubernetesclusterselector: "true"
  produces:
    KubernetesYamls:
      disabled: false
  config:
    outputPath: "deploy/cicd/argocd"
    useDefaultValuesInYamls: false
