name: Build

on:
  push:
    branches:
      - "main"
      - "release-*"

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: info
        uses: konveyor/get-env-info@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.info.outputs.go_version }}
      - run: make ci
      - run: make test-coverage
      - name: upload coverage
        uses: codecov/codecov-action@v1
      - if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "#BD3232"
          SLACK_ICON: https://github.com/actions.png?size=48
          SLACK_MESSAGE: "Build and test failed for move2kube ${{ github.ref }}"
          SLACK_TITLE: Failed
          SLACK_USERNAME: GitHubActions

  run_move2kube_tests:
    needs: [build_and_test]
    name: Run move2kube tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: info
        uses: konveyor/get-env-info@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: pull latest image to reuse layers
        run: |
          docker pull quay.io/konveyor/move2kube:latest || true
          docker pull quay.io/konveyor/move2kube-builder:latest || true
      - run: echo "${{ secrets.QUAY_BOT_PASSWORD }}" | docker login --username "${{ secrets.QUAY_BOT_USERNAME }}" --password-stdin quay.io
      - name: build image
        run: VERSION='${{ github.run_id }}' GO_VERSION='${{ steps.info.outputs.go_version }}' make cmultibuildpush
      - name: run tests in move2kube-tests
        uses: felixp8/dispatch-and-wait@v0.1.0
        with:
          owner: konveyor
          repo: move2kube-tests
          token: ${{ secrets.MOVE2KUBE_PATOKEN }}
          event_type: cli_build
          client_payload: '{"tag": "${{ github.run_id }}", "commit_ref": "${{ github.ref }}"}'
          wait_time: 5
          max_time: 1200
      - if: failure()
        name: delete temporary image from quay
        run: skopeo delete docker://quay.io/konveyor/move2kube:${{ github.run_id }}
      - if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "#BD3232"
          SLACK_ICON: https://github.com/actions.png?size=48
          SLACK_MESSAGE: "Tests on move2kube-tests failed for move2kube ${{ github.ref }}"
          SLACK_TITLE: Failed
          SLACK_USERNAME: GitHubActions

  image_build:
    needs: [run_move2kube_tests]
    name: Image build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: info
        uses: konveyor/get-env-info@v1
      - id: image_tag
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          if [ "$BRANCH" == 'main' ] ; then
            echo "::set-output name=tag::latest"
          else
            echo "::set-output name=tag::$BRANCH"
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: pull latest image to reuse layers
        run: |
          docker pull quay.io/konveyor/move2kube:latest || true
          docker pull quay.io/konveyor/move2kube-builder:latest || true
          docker pull quay.io/konveyor/move2kube:${{ github.run_id }}
      - run: echo "${{ secrets.QUAY_BOT_PASSWORD }}" | docker login --username "${{ secrets.QUAY_BOT_USERNAME }}" --password-stdin quay.io
      - name: build image
        run: VERSION='${{ steps.image_tag.outputs.tag }}' GO_VERSION='${{ steps.info.outputs.go_version }}' make cmultibuildpush
      - if: always()
        name: delete temporary image from quay
        run: skopeo delete docker://quay.io/konveyor/move2kube:${{ github.run_id }}
      - name: trigger move2kube-api build
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.MOVE2KUBE_PATOKEN }}
          script: |
            const other_repo = 'move2kube-api';
            const build_workflow = 'build.yml';
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: other_repo,
              workflow_id: build_workflow,
              ref: context.ref,
            });
      - name: success slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://github.com/actions.png?size=48
          SLACK_MESSAGE: "Built and pushed quay.io/konveyor/move2kube:${{ steps.image_tag.outputs.tag }}"
          SLACK_TITLE: Success
          SLACK_USERNAME: GitHubActions
      - if: failure()
        name: failure slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "#BD3232"
          SLACK_ICON: https://github.com/actions.png?size=48
          SLACK_MESSAGE: "Failed to build and push image quay.io/konveyor/move2kube:${{ steps.image_tag.outputs.tag }}"
          SLACK_TITLE: Failed
          SLACK_USERNAME: GitHubActions
